modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "alwaysbacktank"
version = "${version}"
displayName = "AlwaysBacktank"
authors = "pat600130"
description = '''
Always shows the Create backtank overlay.'''
#logoFile = ""

[[dependencies.alwaysbacktank]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysbacktank]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysbacktank]]
modId = "create"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "alwaysbacktank.mixins.json"
